from __future__ import annotations

TASK_TAXONOMY: dict[str, tuple[str, ...]] = {
    "AI 導入 / 落地": (
        "ai 導入",
        "ai 應用",
        "生成式 ai",
        "ai 工具",
        "copilot",
        "知識搜尋",
        "企業 ai",
    ),
    "需求分析 / 規格訪談": (
        "需求分析",
        "需求訪談",
        "規格",
        "可行性",
        "需求蒐集",
        "requirement",
        "spec",
    ),
    "跨部門協作": (
        "跨部門",
        "協調",
        "溝通窗口",
        "stakeholder",
        "collaborate",
        "合作",
    ),
    "系統整合 / API 串接": (
        "api",
        "串接",
        "整合",
        "integration",
        "web api",
        "服務串接",
    ),
    "模型 / LLM 應用開發": (
        "llm",
        "rag",
        "prompt",
        "agent",
        "machine learning",
        "deep learning",
        "nlp",
        "模型",
    ),
    "資料處理 / 分析": (
        "資料分析",
        "data analysis",
        "etl",
        "資料處理",
        "pipeline",
        "dataset",
        "sql",
    ),
    "流程自動化 / 效率優化": (
        "自動化",
        "效率",
        "優化",
        "流程改善",
        "標準化",
        "流程優化",
    ),
    "部署 / 維運 / 監控": (
        "部署",
        "維運",
        "monitor",
        "monitoring",
        "production",
        "docker",
        "kubernetes",
    ),
    "測試 / 偵錯 / 效能優化": (
        "測試",
        "除錯",
        "debug",
        "效能",
        "良率",
        "dfm",
        "pfmea",
    ),
    "教育訓練 / 文件": (
        "教育訓練",
        "文件",
        "說明",
        "指引",
        "簡報",
        "training",
        "documentation",
    ),
    "專案推進 / PM": (
        "專案",
        "roadmap",
        "進度",
        "milestone",
        "product",
        "pm",
    ),
    "客戶 / 商務溝通": (
        "客戶",
        "client",
        "technical support",
        "使用者",
        "support",
        "商務",
    ),
}

ROLE_KEYWORD_PATTERNS = (
    "工程師",
    "經理",
    "專員",
    "顧問",
    "分析師",
    "設計師",
    "藥師",
    "醫師",
    "護理",
    "老師",
    "教師",
    "講師",
    "pharmacist",
    "engineer",
    "manager",
    "specialist",
    "consultant",
    "analyst",
    "designer",
    "teacher",
    "instructor",
    "nurse",
)

SKILL_TAXONOMY: dict[str, dict[str, tuple[str, ...]]] = {
    "AI / LLM": {
        "LLM": ("llm", "large language model", "大型語言模型"),
        "RAG": ("rag", "retrieval augmented generation"),
        "Prompt Engineering": ("prompt engineering", "prompt", "提示工程"),
        "AI Agent": ("ai agent", "agentic", "智能代理"),
        "Fine-tuning": ("fine tuning", "fine-tuning", "微調"),
        "Machine Learning": ("machine learning", "ml", "機器學習"),
        "Deep Learning": ("deep learning", "深度學習"),
        "NLP": ("nlp", "natural language processing", "自然語言處理"),
        "Computer Vision": ("computer vision", "cv", "影像辨識"),
    },
    "Framework / Tooling": {
        "PyTorch": ("pytorch",),
        "TensorFlow": ("tensorflow",),
        "scikit-learn": ("scikit-learn", "sklearn"),
        "LangChain": ("langchain",),
        "Pandas": ("pandas",),
        "NumPy": ("numpy",),
        "Spark": ("spark", "pyspark"),
        "Airflow": ("airflow",),
    },
    "Programming": {
        "Python": ("python",),
        "JavaScript": ("javascript",),
        "TypeScript": ("typescript",),
        "Java": ("java",),
        "C++": ("c++", "cpp"),
        "Go": ("golang", "go language"),
        "SQL": ("sql", "mysql", "postgresql"),
        "Bash": ("bash", "shell script"),
    },
    "Backend / Data": {
        "API Design": ("rest api", "api design", "api", "接口設計"),
        "Database": ("database", "資料庫", "mysql", "postgresql"),
        "ETL": ("etl", "data pipeline", "資料管線"),
        "Data Analysis": ("data analysis", "資料分析", "analytics"),
        "System Design": ("system design", "架構設計", "microservices"),
        "Vector Database": ("vector database", "向量資料庫"),
    },
    "Cloud / DevOps": {
        "AWS": ("aws",),
        "GCP": ("gcp", "google cloud"),
        "Azure": ("azure",),
        "Docker": ("docker",),
        "Kubernetes": ("kubernetes", "k8s"),
        "Linux": ("linux",),
        "CI/CD": ("ci/cd", "cicd", "continuous integration"),
        "Git": ("git",),
    },
    "Product / PM": {
        "Agile / Scrum": ("agile", "scrum"),
        "Project Management": ("project management", "專案管理"),
        "Product Management": ("product management", "產品管理"),
        "Roadmap": ("roadmap", "產品路線圖"),
        "Stakeholder Management": ("stakeholder", "跨部門溝通", "利害關係人"),
        "Jira": ("jira",),
        "Figma": ("figma",),
    },
    "Application / FAE": {
        "Solution Design": ("solution design", "解決方案設計"),
        "Technical Support": ("technical support", "技術支援"),
        "Customer Communication": ("customer", "client", "客戶溝通"),
        "Requirement Analysis": ("requirement", "需求分析"),
    },
    "Soft Skills": {
        "Communication": ("communication", "溝通"),
        "Problem Solving": ("problem solving", "問題解決"),
        "Collaboration": ("collaboration", "協作"),
        "Leadership": ("leadership", "領導"),
    },
}
